# Generated by Django 3.2.9 on 2021-12-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(max_length=100, unique=True, verbose_name='promo_title')),
                ('promo_text', models.CharField(max_length=100, unique=True, verbose_name='promo_text')),
                ('promo_slogan', models.CharField(max_length=100, unique=True, verbose_name='promo_slogan')),
            ],
        ),
    ]
