# Generated by Django 3.2.9 on 2021-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='promo_accept',
            field=models.BooleanField(default=True, verbose_name='Промоакции'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.BooleanField(default=False, verbose_name='Возраст'),
        ),
    ]
